
server:
  port: 9090
  stored:
    file :
      path : ${UPLOAD_DIR:./uploads}

spring:
  main:
    allow-bean-definition-overriding: true  #config 수정 가능모드

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
        

  #Database 설정
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 50
      minimum-idle: 20
      idle-timeout: 10000
      data-source-properties:
        cachePrepStmts: true #캐쉬 설정 on
        prepStmtCacheSize: 250 #statement 할당 수
        prepStmtCacheSqlLimit: 2048 #sql문서 최대 길이
        useServerPrepStmts: true #최신버전 지원설정

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    database: mysql
    generate-ddl: false
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        generate_statistics: false
        format_sql: true
        use_sql_comments: false
        cache:
          use_second_level_cache: false
          use_query_cache: false
          region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory


  #thymeleaf 설정 > jstl 대용품
  thymeleaf:
    cache: false
    check-template-location: true
    encoding: utf-8
    servlet:
      content-type: text/html
    prefix: file:src/main/resources/templates/  #개발버전, 배포버전은 다르게 써야함.
    suffix: .html

  #코드 수정 시 자동으로 컴파일 & 적용
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true
    restart:
      enabled: true

#mybatis 세팅
mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapper/**/*.xml


#로그 설정
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org:
      springframework:
        boot:
          autoconfigure: OFF
      thymeleaf: OFF
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
